baseurl = "/"
languageCode = "en-us"
title = "Grayson White"
theme = "avicenna"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  interests="Data science, statistics, and the outdoors."
  cv_name= "grayson-white-resume.pdf"

[[params.affilation]]
  name = "Reed College"
  position = "Mathematics & Statistics Undergraduate"
  contact = "grwhite@reed.edu"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/graysonwhite"
  
[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/graysonwwhite"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/graysonwhite13/"


[[params.introduction.paragraph]]
  text="""
  I am a student at Reed College majoring in Mathematics with a concentration in Statistics.
  I grew up on beautiful Orcas Island, WA and moved to Portland, OR in 2017 to pursue my degree.
  My interests include Bayesian statistics, applications of Bayesian methods to environmental
  and econometric settings, data science, and data visualization.
   """

[[params.introduction.paragraph]]
  text="""
  I am currently working as a Data Science for Public Good researcher at Oregon State University for the summer.
  I am working with Dr. Christine Kelly to develop forcasting tools for cost analysis of water and wastewater
  facilities in Oregon small towns and cities in order to
  provide city planners with data driven solutions for planning long term development and financial investments.
   """
   
[[params.introduction.paragraph]]
  text="""
  I have experiance working as a Statistics Tutor at Reed College.
  While working as a tutor I held weekly study sessions for Math 141: Introduction to Probability and Statistics. 
  I provided students with the help needed to answer questions regarding probability and statistics along with questions
  regarding programming in R.
   """



