baseurl = "/"
languageCode = "en-us"
title = "Grayson White"
theme = "avicenna"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  interests="Data science, statistics, hiking, and bicycling."
  cv_name= "grayson-white-resume.pdf"
  blog="test"

[[params.affilation]]
  name = "Reed College"
  position = "Statistics Undergraduate Student"
  contact = "grwhite@reed.edu"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/graysonwhite"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/graysonwhite13/"


[[params.introduction.paragraph]]
  text="""
  I am a student at Reed College majoring in Mathematics with a concentration in Statistics.
  I grew up on beautiful Orcas Island, WA and moved to Portland, OR in 2017 to pursue my degree.
   """

[[params.introduction.paragraph]]
  text="""
  I have accepted a position as a Data Science for Public Good undergraduate scholar at Oregon State University this summer.
  I will be developing forecasting tools for cost analysis of water and wastewater facilities in Oregon small towns and cities.
   """



